name: Nice n Sleazy Festival
favicon: null
layout_spectrum: 0.5527613016311079
typography_spectrum: 0.4855023578274995
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.49263624125160277
  lightness: 0.9634548116009682
  saturation: 0.07540502957999706
  rhythmicContrast: 0.9372889965306967
purpose: []
